# Set theme
remote_theme: daviddarnes/garth

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock
- vendor

# Set plugins
plugins:
- jekyll-paginate
- jekyll-remote-theme

# Site settings
url: 'http://blog.snehacodes.com'
baseurl: ''
title: 'My blog'
description: 'This is my new blog'
permalink: pretty
logo: "https://avatars.githubusercontent.com/u/4494915?s=400&u=7c85e32b2f657fe19d99406ee4b10362c17e1a4f&v=4"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "Hi! My name is Sneha - welcome to my technical blog. Please feel free to click around and let me know if you have any questions!"
